### ISSUE TITLE
installing version 4.5.1 from pypi fails

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-framework#25]
Installing 4.5.1 using pip on an empty enviroment without traists, traitsui and other depedencies will fail with the following error

```python
pip install enable-4.5.1.tar.gz --user
Processing ./enable-4.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    I was called
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-l_EevW-build/setup.py", line 194, in <module>
        write_version_py(filename='enable/_version.py')
      File "/tmp/pip-l_EevW-build/setup.py", line 100, in write_version_py
        raise ImportError("Unable to import git_revision. Try removing "
    ImportError: Unable to import git_revision. Try removing kiva/_version.py and the build directory before building.
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-l_EevW-build
```

**Comment by itziakos** [comment]
wrong repo closing
